In [1]:
import numpy as np

# 샘플 데이터 생성
sample = np.array([2,5,8,1])
print('1D-Array Sample')
print(sample)

1D-Array Sample
[2 5 8 1]


In [2]:
# np.sort() 정렬
result = np.sort(sample)
print('\nResult of np.sort')
print('Result :', result)
print('Original :', sample)


Result of np.sort
Result : [1 2 5 8]
Original : [2 5 8 1]


In [3]:
# [::-1] 실습
print('\nTest[::-1] ')
print('Original :', sample)
print('Result :', sample[::-1] )


Test[::-1] 
Original : [2 5 8 1]
Result : [1 8 5 2]


In [5]:
# 내림차순 정렬

sort_arr = np.sort(sample)
result = sort_arr[::-1]
print('\nDcending Order')
print('Dcending :', result)


Dcending Order
Dcending : [8 5 2 1]


In [6]:
# 샘플 데이터 생성

sample = np.array([[9,11],[5,1]])
print('\n2D-Array Sample')
print(sample)


2D-Array Sample
[[ 9 11]
 [ 5  1]]


In [7]:
# 2차원 배열 정렬 by axis=0

result = np.sort(sample,axis=0)
print('\nnp.sort(axis=0) :')
print(result)



np.sort(axis=0) :
[[ 5  1]
 [ 9 11]]


In [8]:
# 2차원 배열 정렬 by axis=1

result = np.sort(sample,axis=1)
print('\nnp.sort(axis=1) :')
print(result)


np.sort(axis=1) :
[[ 9 11]
 [ 1  5]]


In [9]:
# 샘플 데이터 생성

name = np.array(['John','Samuel','Kate','Mike','Sarah'])
score = np.array([78,84,96,88,82])

In [10]:
# np.argsort() 통해 정렬된 인덱스 값만 반환

sort_indexes = np.argsort(score)
print('\nnp.argsort()')
print('sort indexes :', sort_indexes)


np.argsort()
sort indexes : [0 4 1 3 2]


In [11]:
# 인덱스 값을 통해 컬럼명 조회
print('sort values :', name[sort_indexes])

sort values : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
